Repository Black-D3vil007/Leetcode75, pull requests merged in 2022-10, with the labels that each got.

#1 I want T-Shirt
  KadaneAlgo.cpp
  flipbits.cpp
  maxsumrectangle.cpp
Labels: hacktoberfest-accepted

#2 Hacktoberfest
  Kth_LargestElem.cpp
Labels: hacktoberfest-accepted

#4 I want T-shirt
  README.md
  Seller.html
  kids.html
  login1.html
  offers.html
  product.html
  recoverpassword.html
  rpassword.html
  seller-login.html
  seller-signup.html
Labels: hacktoberfest-accepted

#5 Stack using Queues
  stack_using_queue.cpp
Labels: hacktoberfest-accepted

#6 add java program
  Kids_With_the_Greatest_Number_of_Candies
Labels: hacktoberfest-accepted

#7 Added Solution of the Problem 16. 3Sum Closest
  16. 3Sum Closest
Labels: hacktoberfest-accepted

#9 Create ClimbingStairs.cpp
  ClimbingStairs.cpp
Labels: hacktoberfest-accepted

#10 Added prime-or-not.cpp
  prime-or-not.cpp
Labels: hacktoberfest-accepted

#11 Bubble sort
  bubblesort.cpp
  floodfill.cpp
Labels: hacktoberfest-accepted

#12 Create Best Time to Buy and Sell Stock.cpp
  Best Time to Buy and Sell Stock.cpp
Labels: hacktoberfest-accepted

#14 Create Counting Bits.cpp
  Counting Bits.cpp
Labels: hacktoberfest-accepted

#13 Create Container With Most Water.cpp
  Container With Most Water.cpp
Labels: hacktoberfest-accepted

#15 Payroll Management System Project
  Payroll Management System
Labels: hacktoberfest-accepted

#18 Get_maze
  get maze.cpp
Labels: hacktoberfest-accepted

#19 kruskal algo added
  Kruskal.cpp
Labels: hacktoberfest-accepted

#20 Create Valid Parentheses.cpp
  Valid Parentheses.cpp
Labels: hacktoberfest-accepted

#17 Added Solution Of reverse Linked list
  ReverseLinkedList.cpp
Labels: hacktoberfest-accepted

#16 Create Bubble Sorting an Array using pointers.cpp
  Bubble Sorting an Array using pointers.cpp
Labels: hacktoberfest-accepted

#21 code to change matrix to spiral matrix
  matrix_to_spiral_matrix.cpp
Labels: hacktoberfest-accepted

#24 code to merge two linked list
  merge_two_ll.cpp
Labels: hacktoberfest-accepted

#23 Added a solution of Richest Customer Wealth
  RichestCustomerWealth.java
Labels: hacktoberfest-accepted

#27 added armstrong number program
  Armstrong number.cpp
  Binary_and_Modular_Exponentiation.cpp
Labels: hacktoberfest-accepted

#25 Max freq
  maxfreqofelement.cpp
Labels: hacktoberfest-accepted

#30 Create n queens problem
  n queens problem
Labels: hacktoberfest-accepted

#29 Create Integet to Roman
  Integet to Roman
Labels: hacktoberfest-accepted

#28 Create Longest Increasing Subsequence
  Longest Increasing Subsequence
Labels: hacktoberfest-accepted

#31 Create using_robot_to_print_lexicographically_smallest_string.cpp
  using_robot_to_print_lexicographically_smallest_string.cpp
Labels: hacktoberfest-accepted

#32 Create Longest Valid Parenthesis
  Longest Valid Parenthesis
Labels: hacktoberfest-accepted

#33 Create 2 C language codes
  double_triangle_pattern.c
  square_pattern.c
Labels: hacktoberfest-accepted

#34 Create Fractional Knapsack
  Fractional Knapsack
Labels: hacktoberfest-accepted

#35 Create Postevent_feedback_with_parallaxeffect.html
  Postevent_feedback_with_parallaxeffect.html
Labels: hacktoberfest-accepted

#36 Add a new program check number is even or odd
  even or odd.cpp
Labels: hacktoberfest-accepted

#38 Create quiz.cpp
  quiz.cpp
Labels: hacktoberfest-accepted

#37 Create sudoko.cpp
  sudoko.cpp
Labels: hacktoberfest-accepted

#39 Two Sum IV - Input is a BST
  Two Sum IV - Input is a BST.cpp
Labels: hacktoberfest-accepted

#44 Added a code for longest substring without repeating character
  longest_substring_without_repeating_characters.cpp
Labels: hacktoberfest-accepted

#43 Added solution to Eventual Safe States
  Eventual_safe_states
Labels: hacktoberfest-accepted

#41 ⭐ "Kids_With_the_Greatest_Number_of_Candies" Program JAVA
  Kids_With_the_Greatest_Number_of_Candies.java
Labels: hacktoberfest-accepted

#40 240, 2919 Added
  Concatenation_Array.cpp
  Search_2DMatrix_II.cpp
Labels: hacktoberfest-accepted

#45 Create guessing_the_number.c
  guessing_the_number.c
Labels: hacktoberfest-accepted

#46 codeforces problem 405-A Gravity Flip Solution
  gravityflipProblem.cpp
Labels: hacktoberfest-accepted

#47 The given solution and it's detailed explaination is done
  EditDistance.cpp
Labels: hacktoberfest-accepted

#49 Create Postevent_update_2.html
  Postevent_update_2.html
Labels: hacktoberfest-accepted

#50 README.md Updated
  README.md
Labels: documentation

#59 Create help_classmates.cpp
  help_classmates.cpp
Labels: hacktoberfest-accepted

#58 Added leetcode 162 PeakElement
  PeakElement.java
Labels: hacktoberfest-accepted

#57 temp convert
  TemperatureConversion.cpp
Labels: hacktoberfest-accepted

#56 Create Flower Planting With No Adjacent.cpp
  Flower Planting With No Adjacent.cpp
Labels: hacktoberfest-accepted

#63 Create Number of Islands.cpp
  Number of Islands.cpp
Labels: hacktoberfest-accepted

#62 UPloading happy number to the main branch
  happynumber_taniaban2712.cpp
Labels: hacktoberfest-accepted

#65 152. Maximum Product Subarray Java DP
  152._Maximum_Product_Subarray.java
Labels: hacktoberfest-accepted

#68 1547. Minimum Cost to Cut a Stick (DP Hard) JAVA
  1547._Minimum_Cost_to_Cut_a_Stick.java
Labels: hacktoberfest-accepted

#69 Create 2421. Number of Good Paths
  2421. Number of Good Paths
Labels: hacktoberfest-accepted

#67 Added three important question from leetcode
  CombinationSum.java
  KthSymbol.java
  TargetSum.java
Labels: hacktoberfest-accepted

#72 Uploaded Make A and B equal
  Make A and B equal.cpp
Labels: hacktoberfest-accepted

#71 Increasing Triplet Subsequence Solution
  increasing_triplet_subsequence.cpp
Labels: hacktoberfest-accepted

#70 Create H-index.cpp
  H-index.cpp
Labels: hacktoberfest-accepted

#74 Vending Machine
  Vending Machine
Labels: hacktoberfest-accepted

#75 Calculator Application
  Calculator application
  Fibonacci Series without recursion
Labels: hacktoberfest-accepted

#76 Create 2427. Number of Common Factors.cpp
  2427. Number of Common Factors.cpp
Labels: hacktoberfest-accepted

#77 Create 2427. N509. Fibonacci Numberumber of Common Factors.cpp
  2427. N509. Fibonacci Numberumber of Common Factors.cpp
Labels: hacktoberfest-accepted

#79 Create 412. Fizz Buzz.cpp
  412. Fizz Buzz.cpp
Labels: hacktoberfest-accepted

#80 added a new leetcode problem
  IntegerToRoman.py
Labels: hacktoberfest-accepted

#81 Create 2365 Task scheduler II
  2365-Task-scheduler-ii.cpp
Labels: hacktoberfest-accepted

#82 309_Best_Time_to_Buy_and_Sell_Stock_with_Cooldown
  309_Best_Time_to_Buy_and_Sell_Stock_with_Cooldown.cpp
Labels: hacktoberfest-accepted

#88 SearchInsertPosition.cpp
  SearchInsertPosition.cpp
Labels: hacktoberfest-accepted

#87 Create missingnumber.cpp
  missingnumber.cpp
Labels: hacktoberfest-accepted

#86 QuizGame
  QuizGame.py
Labels: hacktoberfest-accepted

#85 Updated ClimbingStairs and NQueens Problem
  ClimbingStairs.cpp
  n queens problem
Labels: hacktoberfest-accepted

#84 623. Add One Row to Tree
  addOneRowtoTree.cpp
Labels: hacktoberfest-accepted

#83 Created new Solution
  Ugly Number II.cpp
Labels: hacktoberfest-accepted

#92 Factorial.c
  Factorial
Labels: hacktoberfest-accepted

#91 RemoveDuplicatesfromSortedArray.cpp
  RemoveDuplicatesfromSortedArray.cpp
Labels: hacktoberfest-accepted

#90 Create Merge Intervals
  Merge Intervals
Labels: hacktoberfest-accepted

#97 Create Max Area of Island.cpp
  Max Area of Island.cpp
  Remove Duplicates from Sorted List.cpp
Labels: hacktoberfest-accepted

#96 Create 778. Swim_in_Rising_Water
  778. Swim_in_Rising_Water
Labels: hacktoberfest-accepted

#95 Create 773. Sliding_Puzzle
  773. Sliding_Puzzle
Labels: hacktoberfest-accepted

#94 leetcode questions
  Add two nos.cpp
  BFS.cpp
  DFS.cpp
  Disjisktra.cpp
  Flood_fill_algo.cpp
  Unique Paths III.cpp
  check_star_graph.cpp
  longest cycle in graph.cpp
  reverse integers.cpp
  two sum.cpp
Labels: hacktoberfest-accepted

#93 Create 127. Word_Ladder
  127. Word_Ladder
Labels: hacktoberfest-accepted

#101 Create DFA.py
  DFA.py
Labels: hacktoberfest-accepted

#100 Create N-Queen.py
  N-Queen.py
Labels: hacktoberfest-accepted

#99 Create Sudoku python.py
  Sudoku python.py
Labels: hacktoberfest-accepted

#98 Added FCFS Cpu Scheduling
  FCFS.java
Labels: hacktoberfest-accepted

#102 622. Design Circular Queue
  concatenationofConsecutiveBinaryNumbers.cpp
  designCircularQueue.cpp
Labels: hacktoberfest-accepted

#104 add the solution max XOR of two Numbers in Array
  trie_Maximum_XOR.cpp
Labels: hacktoberfest-accepted

#103 added the solution of Coin_Change_2_DP
  Coin_Change_2_DP.cpp
Labels: hacktoberfest-accepted

#105 added the solution of Power Set trie
  Power_Set_trie.cpp
Labels: hacktoberfest-accepted

#107 Remove Duplicates From Subarray ll has bee updated
  Remove duplicates for subarray ll.java
Labels: hacktoberfest-accepted

#111 Added Create Grading Students problem,
  Create Grading Students problem.py
Labels: hacktoberfest-accepted

#112 Balanced_Paranthesis.cpp
  Balanced Paranthesis.cpp
Labels: hacktoberfest-accepted

#113 Add files via upload
  circular_delete.c
  count_dispaly.c
Labels: hacktoberfest-accepted

#114 Matrix Diagonal Sum Java Question ADD
  Matrix_Diagonal_Sum.java
Labels: hacktoberfest-accepted

#116 merge
  1_activity_selec.cpp
  bst.c
  bst_linked.c
  diagonal_matrix.c
  sparse_add.exe
  sparse_create.c
  tree.c
Labels: hacktoberfest-accepted

#117 Merge pull request #1 from Black-D3vil007/main
  1_activity_selec.cpp
  sparse_add.exe
Labels: hacktoberfest-accepted

#119 Create Linked-List-Cycle-Detection.cpp
  Linked-List-Cycle-Detection.cpp
Labels: hacktoberfest-accepted

#122 commit
  1_bfs.cpp
  MaxDifferenceInArray.cpp
Labels: hacktoberfest-accepted

#129 comit
  4_prims.cpp
Labels: hacktoberfest-accepted

#127 Create Trapping Rain Water.cpp
  Trapping Rain Water.cpp
Labels: hacktoberfest-accepted

#125 125-Valid-Palindrome
  125-Valid-Palindrome.cpp
  single_number.cpp
Labels: hacktoberfest-accepted

#124 Kadane's Algorithm added by me
  kadaneAlgorithm.cpp
Labels: hacktoberfest-accepted

#131 Create Number of Pairs Satisfying Inequality.cpp
  Number of Pairs Satisfying Inequality.cpp
Labels: hacktoberfest-accepted

#132 Added two pointer approach in two sum problem
  two sum.cpp
Labels: hacktoberfest-accepted

#134 table_program
  table_program
Labels: hacktoberfest-accepted

#141 Adds leetcode solutions
  1232. Check If It Is a Straight Line.cpp
  1338. Reduce Array Size to The Half.cpp
  1539. Kth Missing Positive Number.cpp
  21. Merge Two Sorted Lists.cpp
  234. Palindrome Linked List.cpp
  274. H-Index.cpp
  326. Power of Three.cpp
  342. Power of Four.cpp
  659. Split Array into Consecutive Subsequences.cpp
  674. Longest Continuous Increasing Subsequence.cpp
  804. Unique Morse Code Words.cpp
  871. Minimum Number of Refueling Stops.cpp
  88. Merge Sorted Array.cpp
  936. Stamping The Sequence.cpp
Labels: hacktoberfest-accepted

#139 Added solution to 2416. Sum of Prefix Scores of Strings
  Sum of Prefix Scores of Strings.cpp
Labels: hacktoberfest-accepted

#140 leetcode gfg contribution
  GFG-Sets_Problem.cpp
Labels: hacktoberfest-accepted

#142 merge it
  1232. Check If It Is a Straight Line.cpp
  125-Valid-Palindrome.cpp
  1338. Reduce Array Size to The Half.cpp
  1539. Kth Missing Positive Number.cpp
  1_bfs.cpp
  21. Merge Two Sorted Lists.cpp
  234. Palindrome Linked List.cpp
  274. H-Index.cpp
  326. Power of Three.cpp
  342. Power of Four.cpp
  4_prims.cpp
  659. Split Array into Consecutive Subsequences.cpp
  674. Longest Continuous Increasing Subsequence.cpp
  804. Unique Morse Code Words.cpp
  871. Minimum Number of Refueling Stops.cpp
  88. Merge Sorted Array.cpp
  936. Stamping The Sequence.cpp
  Balanced Paranthesis.cpp
  Create Grading Students problem.py
  GFG-Sets_Problem.cpp
  Linked-List-Cycle-Detection.cpp
  Matrix_Diagonal_Sum.java
  Number of Pairs Satisfying Inequality.cpp
  Sum of Prefix Scores of Strings.cpp
  Trapping Rain Water.cpp
  bst.c
  bst_linked.c
  circular_delete.c
  count_dispaly.c
  diagonal_matrix.c
  kadaneAlgorithm.cpp
  linked_list_ circular.cpp
  prime-or-not.cpp
  single_number.cpp
  sparse_create.c
  table_program
  tree.c
  two sum.cpp
Labels: help wanted, hacktoberfest-accepted, discussion

#150 Added solution for Edit distance problem in three approach in c++
  72._Edit_Distance.cpp
Labels: hacktoberfest-accepted

#151 136-single-number
  136-single-number
  88-Merge-Sorted-Array.cpp
Labels: hacktoberfest-accepted

#163 New Update
  korasuls_strongly_connected.cpp
Labels: discussion

#158 Goal Parser
  Goal Parser.cpp
Labels: hacktoberfest-accepted

#159 Added Tower of Honoi
  tower_of_honoi.java
Labels: hacktoberfest-accepted

#160 1-two-sums
  1-two-sums.cpp
Labels: hacktoberfest-accepted

#161 Added frequenciesOfElementsInArray.cpp
  frequenciesOfElementsInArray.cpp
Labels: hacktoberfest-accepted

#162 Added some leetcode SQL solutions
  BigCountries.sql
  FindCustomerReferee.sql
  SalesPerson.sql
Labels: hacktoberfest-accepted

#169 Create segregate_even_and_odd_nodes_in_LL.cpp
  segregate_even_and_odd_nodes_in_LL.cpp
Labels: hacktoberfest-accepted

#171 Bubble sort program added
  bubble_sort.cpp
Labels: hacktoberfest-accepted

#175 Added calculator application in python
  calculator_application.py
Labels: hacktoberfest-accepted

#182 Created maximumSubarraySum.cpp
  maximumSubarraySum.cpp
Labels: hacktoberfest-accepted

#185 merge sort program added
  merge_sort.cs
Labels: hacktoberfest-accepted

#188 Pascal
  Pascal.cpp
Labels: hacktoberfest-accepted

#191 Rectangle
  Rectangle.cpp
Labels: hacktoberfest-accepted

#192 Create Minimize_XOR.cpp
  Count_Number_Of_Texts.cpp
  Minimize_XOR.cpp
Labels: hacktoberfest-accepted

#193 Create Bubble_sort.cpp
  Bubble_sort.cpp
Labels: hacktoberfest-accepted

#194 Create 4Sum.cpp
  4Sum.cpp
Labels: hacktoberfest-accepted

#195 Create Binary_search.cpp
  Binary_search.cpp
Labels: hacktoberfest-accepted

#197 Create Rearrange array elements by sign.cpp
  Rearrange array elements by sign.cpp
Labels: hacktoberfest-accepted

#212 created Delete Node in a Linked List.cpp
  Delete Node in a Linked List.cpp
Labels: hacktoberfest-accepted

#215 Calculator
  Calculator.py
Labels: hacktoberfest-accepted

#217 created Next Permutation.java
  Next Permutation.java
Labels: hacktoberfest-accepted

#219 Create Ugly_Number_II.cpp
  Ugly_Number_II.cpp
Labels: hacktoberfest-accepted

#223 Create Design_A_Text_Editor.cpp
  Design_A_Text_Editor.cpp
Labels: hacktoberfest-accepted

#224 Create SetMatrixZero.java
  SetMatrixZero.java
Labels: hacktoberfest-accepted

#227 Mouseactivity
  Mouseactivity.java
Labels: hacktoberfest-accepted

#229 Create longest-increasing-subsequence-ii.cpp
  longest-increasing-subsequence-ii.cpp
Labels: hacktoberfest-accepted

#230 Created solution for combination sum in c++
  Combination_Sum.cpp
Labels: hacktoberfest-accepted

#236 Create TrainglePattern.java
  TrainglePattern.java
Labels: hacktoberfest-accepted

#237 check ASCII value
  ASCII.cpp
Labels: hacktoberfest-accepted

#244 calculate Digit
  calculateDigit.cpp
Labels: hacktoberfest-accepted

#251 Added Leetcode 235. Lowest Common Ancestor of a Binary Search Tree Solution
  235. Lowest Common Ancestor of a Binary Search Tree.cpp
Labels: hacktoberfest-accepted

#252 Create Missingnumber.cpp
  Missingnumber.cpp
Labels: hacktoberfest-accepted

#253 remove String
  removeString.cpp
Labels: hacktoberfest-accepted

#257 Created 692. Top K Frequent Words.cpp
  692. Top K Frequent Words.cpp
Labels: hacktoberfest-accepted

#261 count Solutions
  countSolutions.cpp
Labels: hacktoberfest-accepted

#266 Created 62. Unique Paths.cpp
  62. Unique Paths.cpp
Labels: hacktoberfest-accepted

#272 Create 394. Decode String.cpp
  394. Decode String.cpp
Labels: hacktoberfest-accepted

#275 Added CPP solution of leetcode 2433. Find The Original Array of Prefix XOR
  2428. Maximum Sum of an Hourglass.cpp
  2433.FindTheOriginalArrayofPrefixXor
  2433.FindTheOriginalArrayofPrefixXor.cpp
  bubble_sort.cpp
  tempCodeRunnerFile.cpp
Labels: hacktoberfest-accepted

#279 rotate_bits
  rotate_bits
Labels: hacktoberfest-accepted

#280 Added LeetCode daily problem 14th Oct 2022
  2095_Delete_the_Middle_Node_of_a_Linked_List.java
Labels: hacktoberfest-accepted

#282 Add files via upload
  traping rain water.cpp
Labels: hacktoberfest-accepted
